version: "3"

services:
  web-service:
    #container_name: web-english
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./src/:/var/www
    ports:
      - "8000:80"
    depends_on:
      - app-service


  app-service:
    #container_name: app-english
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./src/:/var/www
    depends_on:
      - db-service


  db-service:
    image: postgres:latest
    #container_name: db-english

  adminer-service:
    image: adminer
    #container_name: adminer-english
    ports:
     - "8080:8080"
