version: "3"

services:
  web-service:
    container_name: web-laravel_API
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./src/:/var/www
    ports:
      - "8000:80"
    depends_on:
      - app-service
    networks:
      laravel_API-network:
        ipv4_address: 172.30.1.1


  app-service:
    container_name: app-laravel_API
    user: "${USER_UID}:${GROUP}"
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./src/:/var/www
    depends_on:
      - db-service
    working_dir: /var/www
    networks:
      laravel_API-network:
        ipv4_address: 172.30.1.2

  db-service:
    env_file:
      - ./src/.env
    container_name: db-laravel_API
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      laravel_API-network:
        ipv4_address: 172.30.1.3

  adminer-service:
    container_name: adminer-laravel_API
    image: adminer
    ports:
      - "8080:8080"
    networks:
      laravel_API-network:
        ipv4_address: 172.30.1.4

networks:
  laravel_API-network:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16